version: "3.2"

services:
  monit:
    build: .
    image: monit
    container_name: monit
    hostname: monit
    ports:
      - 2812:2812
    volumes:
      - ./monitrc:/etc/monitrc
      - ./telegramrc:/etc/telegramrc
    restart: unless-stopped
    user: abc:users
