version: "2"

services:
  monit:
    build: .
    image: monit
    container_name: monit
    hostname: monit
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - PUID=1000
      - PGID=1000
      - TGTOKEN=${TGTOKEN}
      - TGCHATID=${TGCHATID}
    ports:
      - 2812:2812
    volumes:
      - ./monitrc:/etc/monitrc
    restart: unless-stopped
