name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:
    branches:
      - 'main'
    types: [ assigned ]

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/bakebuild.yml@v4
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: monit
      dockerhub_user: thespad
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
