name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/ci.yml@v2
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "monit"
      release_type: "alpine"
      release_url: "edge/main"
      release_name: "monit"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}