#!/usr/bin/with-contenv bash

#Copy defaults
if [ ! -f "/config/monitrc" ]; then
	cp /defaults/monitrc /config/monitrc
fi

if [ ! -f "/config/sendtelegram" ]; then
	cp /defaults/sendtelegram /config/sendtelegram
fi

if [ ! -f "/config/monit2telegram" ]; then
	cp /defaults/monit2telegram /config/monit2telegram
fi

# if [ ! -f "/config/telegramrc" ]; then
# 	cp /defaults/telegramrc /config/telegramrc
# fi

# if [[ -n "$TGTOKEN" ]] && [[ -n "$TGCHATID" ]]; then
# 	printf "TOKEN=$TGTOKEN\nCHATID=$TGCHATID" > /config/telegramrc
# fi

#symlinks for backwards compat
ln -s /config/sendtelegram /usr/local/bin/sendtelegram
ln -s /config/monit2telegram /usr/local/bin/monit2telegram

# set permissions
chown -R abc:abc \
	/config

chmod 700 \
	/config/monitrc
	/config/sendtelegram
	/config/monit2telegram
