#!/usr/bin/with-contenv bash

#Copy defaults
if [ ! -f "/config/monitrc" ]; then
	cp -a /defaults/monitrc /config/monitrc
fi

if [ ! -f "/config/monit2apprise" ]; then
	cp -a /defaults/monit2apprise /config/monit2apprise
fi

# set permissions
chown -R abc:abc \
	/config

chmod 700 \
	/config/monitrc
	/config/monit2apprise
